apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus-example-app
subjects:
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: Developer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: monitoring-edit
